### ISSUE TITLE
Cannot install anything via the extension marketplace

### ISSUE THREAD

**Issue by rusagent** [bitnami/bitnami-docker-opencart#79] opened 2020-04-05 13:30 UTC
I don't even see the extensions/themes/plugins.... 
Check this screenshot.

![image](https://user-images.githubusercontent.com/1582815/78499655-4a8d0180-7752-11ea-9653-8acb0d729852.png)

Also uploading extensions doesn't really work.... Whats going on?

**Comment by rusagent** [comment] 2020-04-05 13:37
I get this error when i upload the materialze theme:

> SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
OK
<b>Warning</b>: rename(/opt/bitnami/opencart/system/library/materializepagination.php): failed to open stream: Permission denied in <b>/opt/bitnami/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b><b>Warning</b>: rename(/bitnami/opencart/system/storage/upload/tmp-ck7C4R0AFo/upload/system/library/materializepagination.php,/opt/bitnami/opencart/system/library/materializepagination.php): Permission denied in <b>/opt/bitnami/opencart/admin/controller/marketplace/install.php</b> on line <b>218</b>{"text":"Applying modifications!","next":"https:\/\/opencart.altendorfer.tech\/admin\/index.php?route=marketplace\/install\/xml&user_token=CPEhhQvG29ZA7dMzS4AdE41O2J0xWNQo&extension_install_id=1"}

**Comment by juan131** [comment] 2020-04-06 07:08
Hi @rusagent 

Could you please take a look to the different suggestions I provided on the issue below?

- https://github.com/bitnami/bitnami-docker-opencart/issues/53

Closing this issue as a duplicate of https://github.com/bitnami/bitnami-docker-opencart/issues/53

**Closed by juan131** 2020-04-06 07:08 UTC

**Comment by rusagent** [comment] 2020-04-06 15:44
Hi - can you please not just close the issue although it still persists? In thread #53 there is no solution for me...

**Comment by juan131** [comment] 2020-04-07 06:35
Then let's reopen #53 but we shouldn't duplicate conversations, so users facing the same issue can find all the different workaround under the same issue.
